site_name: 'reset'
site_description: 'Main documentation for the reset'
repo_url: https://github.com/mallama-org/reset
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'